#!/bin/bash
# gen-seccomp-table.sh — regenerate internal/seccomp/syscalls_amd64.go from
# the vendored kafel amd64 syscall table.
#
# The Go table is the exact set of names kafel accepts on amd64, used by
# seccomp.CombinedWith to reject a per-language `seccomp:` extra that kafel
# would fail to compile (a typo fails fast as internal_error instead of a
# misleading build_failed/runtime_error from nsjail's exit 255).
# Re-run after any nsjail submodule bump:
#   ./scripts/gen-seccomp-table.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/external/nsjail/kafel/src/syscalls/amd64_syscalls.c"
OUT="$ROOT/internal/seccomp/syscalls_amd64.go"

if [ ! -f "$SRC" ]; then
    echo "gen-seccomp-table: vendored kafel table not found: $SRC" >&2
    echo "gen-seccomp-table: is the nsjail submodule initialized? (git submodule update --init)" >&2
    exit 1
fi

NAMES="$(grep -oE '^\s+\{"[a-z0-9_]+"' "$SRC" | grep -oE '"[a-z0-9_]+"' | tr -d '"' | sort -u)"
COUNT="$(printf '%s\n' "$NAMES" | wc -l)"
if [ "$COUNT" -lt 300 ]; then
    echo "gen-seccomp-table: suspiciously few names ($COUNT), refusing to write" >&2
    exit 1
fi

{
    echo "// Code generated by scripts/gen-seccomp-table.sh from the vendored"
    echo "// kafel amd64 table (external/nsjail/kafel/src/syscalls/amd64_syscalls.c)."
    echo "// DO NOT EDIT. Re-run the script after any nsjail submodule bump;"
    echo "// TestSyscallTableInSync fails when the table drifts."
    echo "package seccomp"
    echo ""
    echo "// validSyscalls is the exact set of syscall names kafel accepts on"
    echo "// amd64. CombinedWith rejects any per-language seccomp extra outside"
    echo "// this set (numeric SYSCALL[n] form aside) so a typo fails fast as"
    echo "// internal_error instead of a misleading build_failed/runtime_error"
    echo "// from nsjail's exit 255."
    echo "var validSyscalls = map[string]bool{"
    printf '%s\n' "$NAMES" | sed 's/.*/\t"&": true,/'
    echo "}"
} > "$OUT"

# Emit gofmt-clean output so the checked-in file never trips `gofmt -l`.
if command -v gofmt &> /dev/null; then
    gofmt -w "$OUT"
fi

echo "gen-seccomp-table: wrote $COUNT names to $OUT"
